services:
  frontend:
    container_name: wazz-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      VITE_PORT: 8080

  backend:
    container_name: wazz-app-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: mongodb://mongodb:27017/wazzapp
      JWT_SECRET: MOCKJWTSECRET123
      PORT: 5000
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    container_name: wazz-app-mongodb
    image: mongo
    ports:
      - '27017:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/wazzapp --quiet
      interval: 10s
      timeout: 5s
      retries: 3
